services:
  digitalocean-ddns:
    # image: samuelme/digitalocean-ddns
    container_name: digitalocean-ddns 
    build: .
    ports:
      - "8080:8080"
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
      - DO_DOMAIN_NAME=example.com
      - DO_SUBDOMAIN=home
      - DDNS_PASSWORD=${DDNS_PASSWORD}
